apiVersion: v1
kind: Pod
metadata:
  name: psql-client
spec:
  containers:
    - name: psql
      image: postgres:15
      command: ["sleep", "360000"]
      volumeMounts:
        - name: pgssl
          mountPath: /certs
          readOnly: true
  volumes:
    - name: pgssl
      secret:
        secretName: postgres-ssl
        items:
          - key: root.crt
            path: root.crt
